### ISSUE TITLE
gTile does not work with gnome-shell 3.30

### ISSUE THREAD

**Issue by edgan** [gTile/gTile#46] opened 2018-09-06 18:51 UTC
I am running gnome-shell 3.30. Both the gnome extensions site, and gnome-tweak-tool show gTile is not working. I also don't see the icon in the top panel.

**Comment by scherepanov** [comment] 2018-09-06 19:43
Can you post here debug info?
1) Enable debug in gTile:
tweaks->extensions->gTile preferences-> check "Debug"
2) Logout of gnome
3) login into gnome
4) open terminal.
5) journalctl
6) Go to thevery end of journal (type in "G")
7) Search backwards for gTile entries (enter "?gTile<Enter>")
8)Post here what you will find
Do not forget to disable debuggin afterwards

**Comment by StuntsPT** [comment] 2018-09-06 22:07
Also do not forget that gTile does not yet have gnome-shell 3.30 enabled.
You can try to edit `metadata.json` in the extension directory, and add "3.30" to the "shell-version" array.
You have to add a `,` at the end of line 14, and add a new line after line 14 with : `"3.30"`.

**Comment by luisbc92** [comment] 2018-09-14 04:02
Enabled Debug and checked the log.

The problem is at **extension.js** @ 710: 
    reference to undefined property "screen"
    TypeError: global.screen is undefined.

**Comment by scherepanov** [comment] 2018-09-14 19:38
Something is telling me that after change, gTile is not going to work with gnome-shell v < 3.30.
Can you verify that your changes are working on gnome-shell v3.28?

**Comment by scherepanov** [comment] 2018-09-16 13:15
Merged into master

**Closed by scherepanov** 2018-09-16 13:15 UTC
