### ISSUE TITLE
Sometimes, window behind gTile interface keeps focus. Can't use mouse.

### ISSUE THREAD

**Issue by geektechniquestudios** [gTile/gTile#174] opened 2020-11-15 20:18 UTC
I am unsure what exactly causes this to occur, but it is quite frequent. I will open the gTile gui with "Super + Enter" and go to click on the tiles, and **the mouse will select what is behind the gTile window**. From this point, I am only able to use gTile if I move the window out from behind gTile leaving the desktop as the only selectable medium behind the gTile window.

Ubuntu 20.04.1 with standard Gnome Desktop
32:9 5120x1440 monitor
Installed through Gnome Shell Extensions

If you need any other system info, please don't hesitate to let me know. Thanks for this great software.

**Comment by geektechniquestudios** [comment] 2020-11-15 20:32
![Peek 2020-11-15 15-30](https://user-images.githubusercontent.com/42378648/99196027-aba09d00-2757-11eb-8a12-3d7bcc8897d9.gif)

**Comment by makuser** [comment] 2020-11-17 09:05
Dup of #168 I'd say.

**Comment by geektechniquestudios** [comment] 2020-11-17 17:55
> Dup of #168 I'd say.

They're not the same. #168 claims that only the rightmost column consistently isn't working. I'm experiencing 0 functionality across the entire interface occasionally until I move the window behind gtile.

**Comment by sidambhire** [comment] 2020-11-20 17:24
I'm facing the exact same issues. Installed it a few days ago. Great extension BTW!

**Comment by geektechniquestudios** [comment] 2020-11-20 17:55
> I'm facing the exact same issues. Installed it a few days ago. Great extension BTW!

Hey, thanks for confirming my issue. Would you mind sharing your OS version, and maybe if you're using other gnome shell extensions, could you mention those if there aren't too many? Just trying to figure out why only a few people would experience this.

**Comment by eric-vader** [comment] 2020-11-26 07:33
Confirming this issue on Fedora 32. It's intermittent and doesn't happen for me every time. I am only using this extension.

**Comment by edurenye** [comment] 2020-12-01 10:26
I have the same issue in Ubuntu 20.10.

**Comment by scherepanov** [comment] 2020-12-02 19:55
That is a duplicate of #168

**Closed by scherepanov** 2020-12-02 19:55 UTC

**Comment by geektechniquestudios** [comment] 2020-12-02 20:01
> That is a duplicate of #168

It is definitely not the same bug.

**Comment by scherepanov** [comment] 2020-12-02 20:08
Well, during rewrite to Typescript, bug slipped into code for mouse interface. I am not using mouse, and all tests were fine. Bug went unnoticed for some time, and made it into master.
Internally, it is same bug, with mouse signals not being subscribed properly. If you will dig, mouse interface is actually quite complicated thing. Keyboard shortcuts interface is very simple.
I tried several times to trace mouse operations, but so far no success.

**Comment by geektechniquestudios** [comment] 2020-12-02 20:27
> Well, during rewrite to Typescript, bug slipped into code for mouse interface. I am not using mouse, and all tests were fine. Bug went unnoticed for some time, and made it into master.
> Internally, it is same bug, with mouse signals not being subscribed properly. If you will dig, mouse interface is actually quite complicated thing. Keyboard shortcuts interface is very simple.
> I tried several times to trace mouse operations, but so far no success.

Ah, thanks for the detailed explanation. It is very appreciated. I'll try out an older version prior to .ts integration.

**Comment by eric-vader** [comment] 2020-12-03 02:45
Something fixed it, after i update to the latest version, it seems to be fixed.

**Comment by eric-vader** [comment] 2020-12-03 02:51
> Well, during rewrite to Typescript, bug slipped into code for mouse interface. I am not using mouse, and all tests were fine. Bug went unnoticed for some time, and made it into master.
> Internally, it is same bug, with mouse signals not being subscribed properly. If you will dig, mouse interface is actually quite complicated thing. Keyboard shortcuts interface is very simple.
> I tried several times to trace mouse operations, but so far no success.

I see, I might have some time this weekend to look into the code to try to patch this.
Any hints as to which direction to look will be of great help.

**Comment by scherepanov** [comment] 2020-12-03 16:33
Thanks for offer!
I think you can turn on logging, and track down why mouse hover is not triggered over left- right- most tile in gTile window (i.e. right lower corner tile). I have a very strong suspicion, if you will fix this problem, rest will be working. I tried this for couple hours, but have not found why.
I am thinking about comparing v35 to current code. It was "almost" one-to-one migration from javascript to typescript, and bug was introduced at this time.
Current code contain one more big change, support of monitor-change event and correct destroy of grids on disable. That change should not affect this bug.
Good luck, and keep posted!

**Comment by scherepanov** [comment] 2020-12-06 22:03
Can you look, why buttons on gTile window does not work?
