### ISSUE TITLE
gTile not opening on gnome 3.36.3

### ISSUE THREAD

**Issue by bmn001** [gTile/gTile#162] opened 2020-10-13 19:39 UTC
After updating to the latest gtile, I'm no longer able to enable it.  extensions.gnome.org shows an "error" icon when I try.

I'm running gnome 3.36.3 which is the latest under Ubuntu 20.04.1 LTS.

The log reports the following when I attempt to install/enable:
```
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile Enabling begin
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile Init gnome-shell version 3.36.4 major 3 minor 36
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile Init settings
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile grid-sizes set to 8x6,6x4,4x4
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile Starting...
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile initGrids
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile New Grid for monitor 0
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile ToggleSettingsButton _update event animation
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile ToggleSettingsButton Connect button-press-event
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile ToggleSettingsButton Connect update-toggle
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile ToggleSettingsButtonListener Connect update-toggle
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile ToggleSettingsButton _update event auto-close
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile ToggleSettingsButton Connect button-press-event
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile ToggleSettingsButton Connect update-toggle
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile ToggleSettingsButtonListener Connect update-toggle
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile ActionButton Connect button-press-event
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile AutoTileMainAndList connect button-press-event
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile ActionButton Connect button-press-event
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile AutoTileTwoList connect button-press-event
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile hide true
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile Connect hide-tiling for monitor 0
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile Init grid done
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile Create Button
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: gTile GTileStatusButton _init done
Oct 13 09:17:27 user-XPS-13-9300 gnome-shell[2840]: JS ERROR: Extension gTile@vibou: Error: Extension point conflict: there is already a status indicator for role GTileStatusButton
                                                     addToStatusArea@resource:///org/gnome/shell/ui/panel.js:1111:19
                                                     enable@/home/user/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:645:22
                                                     _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
                                                     loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:349:26
                                                     callback@resource:///org/gnome/shell/ui/extensionDownloader.js:234:39
                                                     gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13
```

**Comment by scherepanov** [comment] 2020-10-13 23:47
In theory, this error will disappear if you will completely remove gTile and then reboot.
Can you check this theory?

**Comment by skymoo** [comment] 2020-10-14 15:37
Been getting this quite a lot recently, the only way I've found to get things working again is to restart `gnome-shell`, i.e. Alt-F2 and then `r`. Only then will gTile start working again. At some point later the same happens and I again need to restart `gnome-shell` again.

I tried removing the gTile extension and rebooting my system, when it comes back up and can reinstall gTile successfully but at some point in the future I receive the same error and need to restart `gnome-shell` again.

**Comment by benhegarty** [comment] 2020-10-14 21:59
@skymoo I'm seeing this exact behaviour too on Ubuntu 20.04, GNOME Shell 3.36.4

**Comment by maciekpoplawski** [comment] 2020-10-15 06:21
same as @benhegarty

**Comment by scherepanov** [comment] 2020-10-15 15:58
That seems to be change in gnome-shell behavior.
I cannot reproduce so far on recent Fedora. 
Most likely, on disable, status icon is not being removed, or something like this.

**Comment by scherepanov** [comment] 2020-10-15 16:02
Can you set hide icon in settings, and see if it fixes problem.
Please post here result

**Comment by skymoo** [comment] 2020-10-15 17:47
Seems to be the same behaviour with the icon hidden, after a while it stops working and I need to restart `gnome-shell` to get it working again.

**Comment by tonisostrat** [comment] 2020-10-15 20:15
Same here. Ubuntu 20.04 with Gnome 3.63.3. Started happening after a system update a week or two ago but I unfortunately cannot pinpoint the exact time.

Changing the icon state doesn't matter because I've had it hidden since the day I installed it.

**Comment by scherepanov** [comment] 2020-10-16 02:24
After investigation, looks like this is a bug in gnome-shell. 
Error is caused by check in line 1111 in panel.js in gnome-shell UI. It will trigger if button already registered on panel with same name, and has not been destroyed.
gTile behave properly - it creates status button on enable, and adds to panel. On disable, status button being destroyed. Exactly as it should.
Error seems to be triggered when gnome-shell goes into sleep (you can cause it by super-L). Then disable is being called. On wake-up, enable is being called, and if button has not been destroyed, it will cause error we see.
Another thing - if panel button set to hide in gTile preferences, it would never been added to panel. So, this error should not appear at all, as button is not added to panel. Fact that error showing up is completely strange. I think it can be two possible explanations 
1) Bug in gnome-shell. I am on 3.36.6-1, and I cannot reproduce it.
2) Some clone of gTile installed on system and registering button with same name, causing this behaviour.

There are two key facts:
1) Hide button on panel do not prevent error. It points to gTile clone installed on system.
2) I cannot reproduce bug. It points to bug in gnome-shell.

One thing to check if gTile really has been disabled, before it is being enabled. Check logs, you should see message "gTile Extension start disabling"

**Comment by rj-david** [comment] 2020-10-16 07:20
Confirming that the error happens when gnome goes into sleep.

Ubuntu 20.04.1
gnome 3.36.3

**Comment by neapovea** [comment] 2020-10-16 09:30
Same error on Ubuntu 20.04.

**Comment by theftf** [comment] 2020-10-16 11:40
Same here with Ubuntu 20.04 it appears to work with one screen, after adding a second screen it stops working.

**Comment by mvnural** [comment] 2020-10-16 20:10
I have the same problem as well but I've never had the icon enabled. Here's the only error message from syslog before the extension crashes and gnome-shell disables it. As others indicated, I can enable gTile after reloading the shell (logout, alt+f2+r, reboot) and it works just fine until the next crash. 

`Oct 13 14:06:02 xxx-Precision-7540 gnome-shell[21022]: JS ERROR: Extension gTile@vibou: TypeError: grid is undefined#012destroyGrids@/home/mnural/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:701:9#012disable@/home/mnural/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:667:5#012_callExtensionDisable@resource:///org/gnome/shell/ui/extensionSystem.js:108:32#012_disableAllExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:624:22#012_disableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:623:52#012_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:641:18#012_emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47#012_sync@resource:///org/gnome/shell/ui/sessionMode.js:198:14#012pushMode@resource:///org/gnome/shell/ui/sessionMode.js:159:14#012activate@resource:///org/gnome/shell/ui/screenShield.js:574:34#012lock@resource:///org/gnome/shell/ui/screenShield.js:623:14#012LockAsync@resource:///org/gnome/shell/ui/shellDBus.js:378:28#012_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:371:35#012_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:404:34`


Ubuntu 20.04.1 
gnome-shell 3.36.3
gTile v38 (from gnome extensions site, last updated on 10/10)

**Comment by scherepanov** [comment] 2020-10-19 16:15
There are two different bugs mixed here: one is about grid, and it is fixed on master. Second is about conflict on status button on panel. 
@mvnural this is different bug, fixed on master. Please try to install from master and post here how it works.
@bmn001 really if icon is hidden, this bug should not show up. In code, if icon is hidden, then button is not being added to panel, and there is no opportunity to hit error that you are showing.
Only possible explanation is that you have some other extension that have status button on panel with same name. Please try to disable all extensions, hide gTile icon, login logout, and error should not show up

**Comment by benhegarty** [comment] 2020-10-19 22:45
I had the same symptom as @mvnural.

@scherepanov I've built/installed from master. Will report here in a few days and let you know how I went :) Thanks for your help!

**Comment by rj-david** [comment] 2020-10-20 06:43
> Confirming that the error happens when gnome goes into sleep.
> 
> Ubuntu 20.04.1
> gnome 3.36.3

I can now also confirm that the error only happens when the icon is displayed

Here are the steps that I used to solve my problem:
1. Go to gTile preferences and untick `Show Icon`
2. Uninstall gTile
3. Restart / Logout
4. Install gTile

Now it is working even if gnome-shell goes to sleep

**Comment by mvnural** [comment] 2020-10-20 14:24
> @mvnural this is different bug, fixed on master. Please try to install from master and post here how it works.

@scherepanov I've been testing the master since yesterday and I'm unable to reproduce the error (and the consequent crash) after many combinations of sleep/wake & dock/undock cycles. It seems #161 have fixed it.

Thanks!

**Comment by scherepanov** [comment] 2020-10-20 19:02
It is hard to read this ticket, as users are reporting here two different bugs - "grid" bug (fixed in #161) and "point conflict" bug.

@mvnural finally, I had a confirmation that #161 is fixing "grid" bug.
Will roll out to EGO.

Based on user feedback in this ticket, "point conflict" bug is fixable by disabling icon. 
It is confirming that bug is in gnome-shell - on button destroy, during going to sleep, class reference is not being removed from panel.
For me, on gnome-shell 3.36.6, this bug is not showing up. It makes me think that upgrade to gnome-shell 3.36-6 would fix "point conflict" bug.

**Comment by scherepanov** [comment] 2020-10-20 19:20
New version of extension, with #161 fix, is pending review on EGO.

**Comment by scherepanov** [comment] 2020-10-20 19:50
I am dumb. EGO do have a button to deactivate extension. I deactivated toxic version of gTile.
Now, regular update from EGO will produce a working gTile for gnome-shell v 3.28 and below.

**Comment by bmn001** [comment] 2020-10-22 22:00
I just upgraded to Ubuntu 20.10 which includes Gnome 3.38.1.  Gtile is v38.

Everything is working in this configuration, and since I'm upgraded I can't provide any other updates on the original bug. :)

**Comment by maciekpoplawski** [comment] 2020-10-23 17:35
Same as @bmn001 :) Finaly working again! :+1:

**Comment by scherepanov** [comment] 2020-10-23 18:28
It appears, we discovered reason for a bug in this ticket.
Would you mind to install gTile from PR #166 and post here, how it works.
That contains fix for a root cause.

**Closed** 2020-12-17 16:44 UTC
