### ISSUE TITLE
Moving window to a different monitor is unreliable

### ISSUE THREAD

**Issue by gonzojive** [gTile/gTile#402] opened 2024-11-13 00:22 UTC
move-to-monitor doesn't actually move my window between different monitors.

Sometimes it does, like if I start the window in monitor 2 (new window in Chrome), drag the window to minotor 1 (my left monitor), then hit the hotkey.

Sometimes it doesn't, like if I start the window in monitor 2 and just hit the hotkey for move-to-monitor.

**Comment by schnz** [comment] 2024-11-13 07:53
Unfortunately I can't reproduce it (with the given information) with my Chromium app on Wayland and latest Gnome.


Please have a look at the [implementation](https://github.com/gTile/gTile/blob/27e7d8ac8cefde9d98d46f2c43c703fdff0db722/src/core/DesktopManager.ts#L168-L179) - which is straight forward. Other than the window being active, it just invokes the [move_to_monitor](https://gjs-docs.gnome.org/meta15~15/meta.window#method-move_to_monitor) method directly from the GJS libs. Maybe it helps you to identify the reason why it doesn't work in your scenario.

**Comment by gonzojive** [comment] 2024-11-15 01:32
I recall having issues with the monitors list getting out of sync with reality and needing to query gnome to get an accurate monitor list.

I will try to install the plugin and add logging to debug.

FWIW: 

```
$ gnome-shell --version
GNOME Shell 46.3.1
```

**Comment by gonzojive** [comment] 2024-11-15 02:45
I added some logging. target.move_to_monitor(monitorIdx) is being called as I would expect. However, it is not having the intended effect of actually moving the window from one monitor to another.

A pattern I'm observing is this problems occurs only when the top of window being moved is close to the top of the screen. On the monitor I'm moving the window to, there is a system menu bar at the very top (maybe 20 pixels high). I suspect the move is failing because the current top left corner of the window is not a valid position for the target monitor.

**Comment by gonzojive** [comment] 2024-11-15 02:54
I'm guessing this is the move_to_monitor code that's not behaving as expected. I can't quite follow the logic.

https://github.com/GNOME/mutter/blob/43cad8d68b9597689a6dbb938975af0591cb3f14/src/core/window.c#L4277-L4331

**Comment by schnz** [comment] 2024-11-15 07:35
> A pattern I'm observing is this problems occurs only when the top of window being moved is close to the top of the screen. On the monitor I'm moving the window to, there is a system menu bar at the very top (maybe 20 pixels high). I suspect the move is failing because the current top left corner of the window is not a valid position for the target monitor.

This sounds like a very reasonable assumption. I'll have a look this evening or tomorrow on to the code snippet in the mutter repository that you posted. Is the system menu bar coming from another Gnome extension?

**Comment by gonzojive** [comment] 2024-11-15 16:51
> Hi @gonzojive I cannot really test move between monitors, now I have single 4K 43'' monitor. And I am on older version of Ubuntu, and still running gTile v 44, and it is now a completely different codebase.
> 
> Gnome has a built-in move between monitors, by default mapped to Super-Shift - Arrows. I used it extensively when I had multiple monitors, works just fine. I see no point to re-implement overlapping Gnome-shell functionality. You are not going to make it better, and you are facing all problems described above.
> 
> Though, I never objected if people want to add some new features, as soon as they will properly maintain them.

I agree with you in theory. Practically it is much easier to update this plugin than make changes to gnome and fix their bug.

Also, FWIW, the same functionality in gTile (move to next monitor with wrapping) isn't available in Gnome. "Move to right" does move a monitor to the far-left monitor if a window is on the far-right monitor.

![image](https://github.com/user-attachments/assets/1a29cd5d-3d64-472b-9cbe-95c7e3238e69)

**Comment by scherepanov** [comment] 2024-11-15 17:36
@gonzojive sorry cannot test it.
@schnz can you look on this commit?

**Comment by schnz** [comment] 2024-11-15 17:47
> @gonzojive sorry cannot test it. @schnz can you look on this commit?

I suppose it's not ready for being reviewed.


@gonzojive , can you give me further information with regards to my last question?

**Comment by schnz** [comment] 2024-11-15 18:52
I see. I was curious to try if I can reproduce it. But the system bar doesn't seem to be the issue at hand. On my system, windows near the top of the screen still rotate across monitors as desired.

**Comment by gonzojive** [comment] 2024-12-20 18:08
https://github.com/gTile/gTile/pull/403 is in a state where it can be merged. I observe this on two different computers.

I have a further enhancement planned where the move to a different monitor will try to maintain the same grid position it's currently in using these steps:
1) When moving window W from M_origin to M_target, transform the position of W in M_origin to a position in a 100x100 grid.
2) Move the window to the target using `applySelection` with the 100x100 grid spec and inferred position of the window.

**Comment by schnz** [comment] 2024-12-20 19:41
The change would alter the behavior (which is literally called [`move_to_monitor`](https://gjs-docs.gnome.org/meta13~13/meta.window#method-move_to_monitor)) to something different: Resizing and repositioning the window to a fixed (relative) position, size and aspect ratio (on a different monitor).

This is too much of a workaround in my eyes for a bug which is neither reproducible nor is the reason of it known, nor should it be fixed by a change in behavior. In my eyes it would be better to identify the steps required to reproduce the bug and move forward from thereon, e.g. by creating an [upstream issue](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues) in case that the bug is in Gnome itself.

**Comment by gonzojive** [comment] 2024-12-20 19:49
I don't have time to make a reproduction because that is difficult to do
given Gnome's complexity. But I can file a bug eventually.

I don't find the change in behavior a concern because if someone wants the
gnome move to monitor function, they can use the gnome shortcuts. This is a
gtile specific move to monitor function that I actually expect to change
size and aspect ratio to maintain some level of grid.

**Comment by schnz** [comment] 2024-12-20 20:13
> This is a gtile specific move to monitor function that I actually expect to change size and aspect ratio to maintain some level of grid

Fair enough. I've provided some feedback in your PR. Ultimately I'll leave the decision to @scherepanov due to my lack of knowledge about how this feature was supposed to work in the extension. And he needs to upload and publish the new extension anyway  - should it be merged.

**Comment by gonzojive** [comment] 2024-12-20 20:31
It's ok if it doesn't merge. I will just use a fork until gnome fixes the
bug, which will probably be a few years.

**Closed** 2024-12-29 14:22 UTC
