### ISSUE TITLE
RFC: Move to Bazel and Typescript

### ISSUE THREAD

**Issue by JMurph2015** [gTile/gTile#93] opened 2019-09-06 06:45 UTC
I'm going to make a second attempt at doing this, following on #35.  Except I don't plan to do any of the following:
- Add new features
- Change the behavior of existing features
- Break anything (at least before the final merge)

I think this would generally help the maintainability of the codebase and perhaps make some leads for testing.

**Comment by scherepanov** [comment] 2019-09-06 14:40
That would be a very welcome change
Very unfortunately that code was incomplete and buggy.

**Comment by JMurph2015** [comment] 2019-09-09 07:31
My work so far has led me toward a near full-rewrite, but we'll see how far I can get on this.  Basically, in the name of modularity, I'm trying to structure it around a big class that delegates to a bunch of smaller classes for various functions, but that's pretty fundamentally opposed to the global variable approach taken in the current code.  I'll push what is happening so far (not a ton) to my fork and if anyone wants to help feel free to reach out.

**Comment by scherepanov** [comment] 2019-09-09 13:46
Yes full rewrite would be a god approach.
I will try your code when ready.

**Comment by murbanowicz** [comment] 2019-11-27 07:06
@JMurph2015 Could you point me to the branch anywhere? I could try to help. We can get in touch and you can point me to the issues you have with TypeScript and I could try to help.

**Comment by scherepanov** [comment] 2019-11-27 13:47
After looking on general code structure, I have several suggestions:
1) Top-level object that contains all grids on all monitors.
2) Separate object that contain all autotiling
Of course, minimum number of global vars.
And no global functions, everything inside objects.
Pretty much in line what @JMurph2015 mention above.

**Comment by JMurph2015** [comment] 2019-12-02 08:51
Hi @murbanowicz I pushed some code to [JMurph2015/gTile](https://github.com/JMurph2015/gTile) on the "bazel" branch.  It's a near full re-write so it's a rather large undertaking.  Also I haven't been putting in as much time on this project as I've wanted to recently, so that's part of it.

**Comment by scherepanov** [comment] 2019-12-02 19:07
@murbanowicz go ahead with rewrite. Let me know if you need help. At least I can test to see of it works properly.

**Comment by JMurph2015** [comment] 2019-12-23 20:39
@murbanowicz so on further thought, it might be better to first rewrite it in ES6 with classes etc, but no Typescript-Javascript interop hell.  Then once we have that figured out, it would only take figuring the interop out to move to Typescript.

**Comment by JMurph2015** [comment] 2019-12-24 05:04
I uploaded a branch called "es6" on my fork

**Comment by gonzojive** [comment] 2020-07-31 03:31
Hi all, original author of the bazelify branch here. I didn't notice this discussion or that in #35 until now because my beloved gTile extension isn't working in Ubuntu 20.04, and I'm fixing it up. Sorry for the delay!

Of course, it would be cool to see the changes merged upstream so I could benefit from all the other contributors' work. I wrote everything for my own personal use and didn't notice the bugs mentioned, probably because I don't use all the features of gTile. Perhaps the bugs could be fixed by way of introducing tests that reproduce them, then squashing. It would be much easier to catch regressions with better tests (and speaking from my experience with gTile so far, most test-driven development works pretty well for this app).

If I were doing the work, I would skip the ES6 rewrite and go directly to Typescript. Fixing all the Typescript warnings/errors is part of that sweet cycle of dopamine release we coders know and love.

I may have missed the boat already, but I just pushed some changes into [gonzojive/gTile's bazelify branch](https://github.com/gonzojive/gTile/tree/bazelify) to update the code to work with the latest rules_nodejs. Not everything is working again yet, but hopefully it will be by the end of the weekend.

**Comment by scherepanov** [comment] 2020-07-31 12:29
Well, move to Typescript would be a very welcome.
Can you just taking current code and convert to typescript?
If you already did it once, would not be a very hard task.
I will help with testing all functionality.
Apart from re-implementing full functionality of gTile in Typescript, I do not see how your changes can be merged with other contributors work. Other options would be to release your code as separate extension... does not make much sense, as users do not care about underlying code, they care only about functionality.
For Ubuntu 20.04 problem, most likely it is a bug in gnome-shell, will be fixed by simple upgrade of gnome-shell. see #132

**Comment by scherepanov** [comment] 2020-07-31 15:14
I think request to rewrite everything in Typescript is unreasonable. 
May be, we should take a staged approach.
First, take current code and one-to-one convert to Typescript. We will commit it to master.
Next, make build bazelified. Again, we will commit to master.
Next, we can take components one-by-one and rewrite, each time committing to master.
Idea is that each your step is not very big, and result of each step committed to master, and usable in production.
Otherwise, you are spending a lot of efforts, but results are not available to community.

**Comment by gonzojive** [comment] 2020-08-01 16:22
> I think request to rewrite everything in Typescript is unreasonable.
> May be, we should take a staged approach.
> First, take current code and one-to-one convert to Typescript. We will commit it to master.
> Next, make build bazelified. Again, we will commit to master.
> Next, we can take components one-by-one and rewrite, each time committing to master.
> Idea is that each your step is not very big, and result of each step committed to master, and usable in production.
> Otherwise, you are spending a lot of efforts, but results are not available to community.

I only have experience making a Typescript project that uses Bazel to build, so for me it is easier if the approach is not entirely sequenced as proposed. I have taken an initial step in the pull request. Although it does involve converting `extension.js` to Typescript, by using the [any type](https://www.typescriptlang.org/docs/handbook/basic-types.html#any), not many code changes are necessary. Stricter typing can (and probably should) be added later.

One question I had while working: What reference do you use to know what Gnome APIs are available?  Is [gjs-docs.gnome.org](https://gjs-docs.gnome.org/) the canonical source of truth? Could [github.com/sammydre/ts-for-gjs](https://github.com/sammydre/ts-for-gjs) be used to obtain 'typings'?

**Comment by scherepanov** [comment] 2020-08-04 20:38
You are asking very interesting question, I really do not know answer how to get reference to available Gnome APIs.
Only thing, I periodically get requests from users who are running older versions of gnome, like 3.22. I think gTile should continue to work on reasonably old gnome-shell versions.

**Closed** 2020-12-17 16:39 UTC
Labels: speculative
