### ISSUE TITLE
gTile is not starting anymore

### ISSUE THREAD

**Issue by lykius** [gTile/gTile#375] opened 2024-03-04 13:34 UTC
gTile is not starting anymore on my system (Ubuntu 22.04), it was working fine until a couple of weeks ago and it stopped working probably after some OS update.

Things that I tried:

- starting it manually from the browser extensions manager --> the button goes back to "OFF" automatically
- starting it manually from the terminal with `gnome-extensions enable gTile@vibou` --> no error shown on the terminal

If I type `gnome-extensions info gTile@vibou` in the terminal I get:
```
gTile@vibou
  Name: gTile
  Description: Tile windows on a grid.
  Path: /home/XXXXX/.local/share/gnome-shell/extensions/gTile@vibou
  URL: https://github.com/gTile/gTile
  Version: 52
  State: INITIALIZED
```

Any idea of what is happening? How can I debug the problem?

Thanks in advance!!

**Comment by schnz** [comment] 2024-03-04 14:28
Hey lykius,

unless you upgraded Gnome to version 45 (which is not available for Ubuntu 22.04 as far as I am aware), there is nothing that comes to mind.  However, you could check the `journalctl` messages while trying to activate the extension:

```
journalctl -f /usr/bin/gjs /usr/bin/gnome-shell
```

**Comment by scherepanov** [comment] 2024-03-04 17:55
Login/logout

**Comment by lykius** [comment] 2024-03-04 17:59
Hi scherepanov,

> Login/logout

I rebooted the system several times and nothing changed. I also tried to uninstall/re-install gTile, but still no luck.

**Comment by scherepanov** [comment] 2024-03-04 19:24
Try 
journalctl | grep gTile

You should see some error close to the end of output.

**Comment by lykius** [comment] 2024-03-05 07:43
This is the output of `journalctl | grep gTile` immediately after system boot:
```
mar 05 08:35:25 nyx gsd-media-keys[6738]: [6981] Unable to check extensions updates: 405 Client Error: Method Not Allowed for url: https://extensions.gnome.org/update-info/?shell_version=42.9&installed=%7B%22gTile%40vibou%22%3A+%7B%22version%22%3A+52%7D%7D
mar 05 08:35:45 nyx dbus-daemon[2102]: [session uid=1000 pid=2102] Activating service name='org.gnome.Shell.Extensions' requested by ':1.162' (uid=1000 pid=7144 comm="gnome-extensions enable gTile@vibou " label="unconfined")
mar 05 08:36:58 nyx dbus-daemon[2102]: [session uid=1000 pid=2102] Activating service name='org.gnome.Shell.Extensions' requested by ':1.164' (uid=1000 pid=7412 comm="gnome-extensions disable gTile@vibou " label="unconfined")
```

Then I tried again to uninstall/re-install and this is the output:
```
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/settings.js
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/stylesheet.css
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/LICENSE
mar 05 08:38:44 nyx gnome-shell[7711]:    creating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/
mar 05 08:38:44 nyx gnome-shell[7711]:    creating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/
mar 05 08:38:44 nyx gnome-shell[7711]:    creating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/dark/
mar 05 08:38:44 nyx gnome-shell[7711]:    creating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/dark/16/
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/dark/16/animation.png
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/dark/16/auto-close.png
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/dark/16/auto-tile-0.png
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/dark/16/auto-tile-1.png
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/dark/16/close.png
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/dark/16/scale.png
mar 05 08:38:44 nyx gnome-shell[7711]:    creating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/dark/32/
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/dark/32/animation.png
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/dark/32/auto-close.png
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/dark/32/auto-tile-0.png
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/dark/32/auto-tile-1.png
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/dark/32/close.png
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/dark/32/scale.png
mar 05 08:38:44 nyx gnome-shell[7711]:    creating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/dark/48/
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/dark/48/animation.png
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/dark/48/auto-close.png
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/dark/48/auto-tile-0.png
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/dark/48/auto-tile-1.png
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/dark/48/close.png
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/dark/48/scale.png
mar 05 08:38:44 nyx gnome-shell[7711]:    creating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/light/
mar 05 08:38:44 nyx gnome-shell[7711]:    creating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/light/16/
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/light/16/animation.png
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/light/16/auto-close.png
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/light/16/auto-tile-0.png
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/light/16/auto-tile-1.png
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/light/16/close.png
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/light/16/scale.png
mar 05 08:38:44 nyx gnome-shell[7711]:    creating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/light/32/
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/light/32/animation.png
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/light/32/auto-close.png
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/light/32/auto-tile-0.png
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/light/32/auto-tile-1.png
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/light/32/close.png
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/light/32/scale.png
mar 05 08:38:44 nyx gnome-shell[7711]:    creating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/light/48/
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/light/48/animation.png
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/light/48/auto-close.png
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/light/48/auto-tile-0.png
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/light/48/auto-tile-1.png
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/light/48/close.png
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/icons/light/48/scale.png
mar 05 08:38:44 nyx gnome-shell[7711]:    creating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/launcher/
mar 05 08:38:44 nyx gnome-shell[7711]:    creating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/launcher/dark/
mar 05 08:38:44 nyx gnome-shell[7711]:    creating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/launcher/dark/16/
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/launcher/dark/16/active.png
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/launcher/dark/16/default.png
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/launcher/dark/16/hover.png
mar 05 08:38:44 nyx gnome-shell[7711]:    creating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/launcher/light/
mar 05 08:38:44 nyx gnome-shell[7711]:    creating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/launcher/light/16/
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/launcher/light/16/active.png
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/launcher/light/16/default.png
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/images/launcher/light/16/hover.png
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/prefs.js
mar 05 08:38:44 nyx gnome-shell[7711]:    creating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/schemas/
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/schemas/org.gnome.shell.extensions.gtile.gschema.xml
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/schemas/gschemas.compiled
mar 05 08:38:44 nyx gnome-shell[7711]:   inflating: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/extension.js
mar 05 08:38:44 nyx gnome-shell[7711]:  extracting: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/metadata.json
```
Is it helpful?

**Comment by lykius** [comment] 2024-03-13 09:56
I've been running `journalctl | grep gTile` after every reboot, but I never saw anything useful.
Today I found the following error:
```
gjs[9440]: JS ERROR: RangeError: Provided GType name 'gTile.IntSelect' is not valid; automatically sanitized to 'gTile_IntSelect' @/home/lykius/.local/share/gnome-shell/extensions/gTile@vibou/prefs.js:525:27
```
Is it relevant?

**Comment by schnz** [comment] 2024-03-13 11:18
> Is it relevant?

At least not for debugging why the extension itself doesn't work. The `prefs.js` file is only relevant to the settings dialog of the extension.

That being said, I doubt that the non-functioning of the extension is inherent to the extensions itself. It's the latest version  that is still compatible with the pre-45 Gnome environment. It is still being used by a lot of people that, like you, are using Ubuntu 22.04 as a daily driver.

To me, the lack of error messages indicates something wrong with your local setup/PC. Maybe its something as simple as a permission error. But maybe its also a corrupted OS.

**Comment by lykius** [comment] 2024-03-13 12:56
I see. It's really weird that the extension stopped working one day to the next.
I guess I'll have to wait to reinstall Ubuntu :-(

**Comment by schnz** [comment] 2024-03-13 14:15
> I see. It's really weird that the extension stopped working one day to the next. I guess I'll have to wait to reinstall Ubuntu :-(

Reinstalling might be a bit of an overreaction here. But try to locate the cause of the erroneous behavior outside of gTile. For instance, create a new user account and try to install the extension there.

**Comment by lykius** [comment] 2024-03-18 09:30
Hey @schnz, sorry for the late reply.
gTile works fine in a new user account! So it's something corrupted/broken in my account...
Which is the proper way to uninstall completely gTile to try a clean installation?

**Comment by lykius** [comment] 2024-03-20 08:50
No luck :-(
I followed every step but when I try to install gtile from the browser extension the button goes "ON" and "OFF" by itself with no error.

Here's a screencast (not really useful, I know):
[Screencast from 20-03-2024 09:45:15.webm](https://github.com/gTile/gTile/assets/23708868/dbfdfd18-49c4-49cb-be84-dffbd69413c2)

The only other thing that comes to my mind is a warning in the gnome browser extension: "Your native host connector do not support following APIs: v6. Probably you should upgrade native host connector or install plugins for missing APIs. Refer [documentation](https://wiki.gnome.org/Projects/GnomeShellIntegrationForChrome/Installation) for instructions.". I already checked the documentation, but apparently the connector cannot be updated on Ubuntu 22.

Thanks for all the help so far, let me know if you have any other ideas to try.

**Comment by schnz** [comment] 2024-03-20 08:55
> The only other thing that comes to my mind is a warning in the gnome browser extension: "Your native host connector do not support following APIs: v6. Probably you should upgrade native host connector or install plugins for missing APIs. 

Sounds like a helpful message to me. Have you tried to install the extension manually/locally, i.e. download the .zip file from extensions.gnome.org for your Gnome version and then `gnome-extensions install ~/Downloads/gTile[...].zip`?

**Comment by lykius** [comment] 2024-03-20 17:50
`gnome-extensions install ~/Downloads/gTile[...].zip` runs with no output at all.
One thing that I noticed is that after the installation (either from browser or manually), if I run `gsettings list-recursively org.gnome.shell.extensions.gtile` I still get `No such schema “org.gnome.shell.extensions.gtile”`.

**Comment by schnz** [comment] 2024-03-20 19:04
Manual installation requires you to restart the shell session (also check the README.md for a full guide on manual extension installation)

**Comment by lykius** [comment] 2024-03-21 15:08
I tried with a couple of different versions, v53 and v58, with manual installation and restarting the whole system after installation.
The installation doesn't print anything. After rebooting, `gnome-extensions list` shows `gTile@vibou` among the installed extensions. `gnome-extensions show gTile@vibou` produces the following output:
```
gTile@vibou
  Name: gTile
  Description: Tile windows on a grid
  Path: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou
  URL: https://github.com/gTile
  Version: 53
  State: OUT OF DATE
```
and `gsettings list-recursively org.gnome.shell.extensions.gtile` gives:
```
No such schema “org.gnome.shell.extensions.gtile”
```

**Comment by schnz** [comment] 2024-03-21 15:47
You need version 52.. Version 53+ is _only_ for Gnome 45 (as of today, it should also work in Gnome 46).

I suppose you also have enabled the extension (`gnome-extensions enable gTile@vibou`) after the installation & shell-session restart. If that doesn't help, then I am out of suggestions. I will close this issue for now, as it is obviously related to your user (or home directory). However, feel free to continue posting.

**Closed by schnz** 2024-03-21 15:47 UTC
Labels: not a bug

**Comment by lykius** [comment] 2024-03-21 16:39
> You need version 52

Yep, I tried 53 since I couldn't find the release tar for version 52 on github.
Tried again with manual installation of version 52 downloading it from gnome extensions, but no luck, `gnome-extensions show gTile@vibou` prints:
```
gTile@vibou
  Name: gTile
  Description: Tile windows on a grid.
  Path: /home/lykius/.local/share/gnome-shell/extensions/gTile@vibou
  URL: https://github.com/gTile/gTile
  Version: 52
  State: INITIALIZED  <--- this is different
```

Anyway, thanks for all the help, I'll post the solution if I find it.

**Comment by lykius** [comment] 2024-06-12 13:16
I just solved it, completely randomly... I'll post here what I did in case somebody else has the same problem.

I installed `gnome-shell-extension-prefs` with:
```
sudo apt install gnome-shell-extension-prefs
```
This allowed me to use `gnome-extensions-app`, a simple GUI to interact with gnome shell extensions.
Well, there was a toggle button to enable extensions globally that was turned off, by turning it on gTile was finally enabled once again!

I don't remember disabling extensions in any possible way. @schnz do you have any idea about what could have happened?

**Comment by schnz** [comment] 2024-06-12 13:35
Glad you found the solution!

IIRC, when installing an extension with the `gnome-extensions` CLI tool, you have to enable the extension afterwards explictily (in the way you mentioned in your opening post). I assume in the process of uninstalling and installing the extension you simply forgot to activate it afterwards.

**Comment by lykius** [comment] 2024-06-12 13:51
That's not it.
I tried `gnome-extensions enable gTile@vibou` many times, but the status remained `INITIALIZED`.

The button in the `gnome-extensions-app` is not the gTile enable button, is a global flag for all the extensions (I use only gTile so I didn't notice that also other extensions would have been disabled). After toggling this global button, the gTile button switched to enabled automatically.

Somehow extensions were globally disabled, I don't know why.

Anyway, thanks again for the support.

**Comment by TomHarrop** [comment] 2024-08-21 23:13
@lykius  thanks for posting this, I just had the exact same issue on Ubuntu 22.04 and your fix using `gnome-shell-extension-prefs` worked for me too.
