### ISSUE TITLE
gTile pane not showing correctly on all displays

### ISSUE THREAD

**Issue by fjssilva** [gTile/gTile#185] opened 2021-01-08 10:51 UTC
In a multi monitor setup, only one of the gTile panes is displayed correctly with all options. Namely the grid selection buttons only show on one screen:

![image](https://user-images.githubusercontent.com/10222686/104006663-b0556080-519e-11eb-9f35-3c9552fe704d.png)
vs
![image](https://user-images.githubusercontent.com/10222686/104006595-9c116380-519e-11eb-91ec-69581ce18788.png)

I use a three-monitor setup and, in my case, only the pane on the rightmost screen is correct, the other two are missing the "4x4" and "6x4" buttons. My main screen is the middle one. This does not depend on what is the active screen or application at the moment the shortcut is activated. It also behaves the same when activating gTile via top bar tool icon. I configured gTile with different grids but default values did the same too.

Thanks

**Comment by scherepanov** [comment] 2021-01-12 14:22
That is definitely a bug.
Unfortunately, working from home I have only one (though huge 43'') monitor.. my multi-monitor setup is at office.
Fix will have to wait till I will get back to office.

**Comment by scherepanov** [comment] 2021-01-30 21:56
Just upgraded to Fedora 33, gnome-shell 3.38.3, and connected second monitor.
Not reproducible, works as expected.

**Comment by fjssilva** [comment] 2021-02-01 11:44
I just tried with Ubuntu 20.04.1 Live and it does exactly the same - the two grid buttons only show in the rightmost screen. This time I tried on a different computer with two screens only.

So far I tested with Gnome 3.36.3 (from Ubuntu Live) and 3.36.8 (after updates) and both show the same symptoms.

Can you please re-open this?

**Comment by scherepanov** [comment] 2021-02-01 13:48
It is possible to be a bug in gnome, fixed on gnome-shell 3.38.3. 
I’d like to ask you to upgrade gnome-shell, but it can be hard to do.

**Comment by fjssilva** [comment] 2021-02-01 16:03
> It is possible to be a bug in gnome, fixed on gnome-shell 3.38.3.
> I’d like to ask you to upgrade gnome-shell, but it can be hard to do.

I'll try to do it when I can. I can't promise anything as my time for this is very short.
I'll let you know if I find anything new.
Thanks

**Comment by scherepanov** [comment] 2021-02-23 01:45
Looks like a bug in gnome-shell, fixed with recent updates.

**Closed** 2021-02-23 01:44 UTC
Labels: bug
