### ISSUE TITLE
Auto-Close Not Working With Accelerator Keybindings

### ISSUE THREAD

**Issue by mchristiansen** [gTile/gTile#248] opened 2021-11-05 02:55 UTC
With the auto-close option selected after repositioning a window using an accelerator keybinding the gTile overlay remains open. Is this intended behavior? The overlay correctly closes when clicking and resizing using the grid.

DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.1.6
DISTRIB_CODENAME=Pahvo
DISTRIB_DESCRIPTION="Manjaro Linux"

GNOME Version 40.4.0
gTile Version 44

**Comment by scherepanov** [comment] 2021-11-20 13:57
Yes, it is intended behavior.
Prime idea behind accelerator keyboard shortcuts is that you are not opening GUI. Goal is to save you several keyboard actions.
Functionality of keyboard shortcuts is separate from GUI.

Looking on this issue more critically, I think the way gTile behave is natural, and this kind of behavior would be expected by users. Like quickly move window to corner, and then adjust position/size with movement keys. Though, of course, this is my own impression.

**Comment by mchristiansen** [comment] 2021-11-21 02:42
I've found that I use a maximum of about 8-10 window sizes total, which is enough that finding easy to remember and use global keybindings for all of them is impossible, but few enough that once activating the GUI using a more obscure keybinding, then using L for left half of screen, R for right half, T for top half, etc and having the GUI go away gives me quick two-action shortcut for window movements without the need for more than one global shortcut. Currently as far as I can tell it requires an additional toggle of the global keyboard shortcut to dismiss the GUI, which is what I'd like to avoid since my short list of keybindings pretty much covers all my needs.

Is there's a way to configure this behavior that I'm missing? If not and you just consider it out of scope or not in line with the desired gTile behavior, I totally understand. But I feel like this option for accelerator keyboard shortcuts when global presets are disabled would save a keyboard action for me without over complicating global shortcut configuration.

**Comment by scherepanov** [comment] 2021-11-21 15:32
Seems to be you have a valid case, why GUI should close after keyboard preset.
While you have a valid idea what needs to be done, IMHO it will be useful for only very small fraction of gTile users. Oddly enough, vast majority of users are using mouse interface and will not be interested. So, you have to code by yourself.
Do coding and submit PR.
We need to keep current behavior. Add settings to Preferences "Auto close GUI on keyboard shortcut", default disabled. Add feature description to README.md.
If you cannot do coding, I will change this ticket to "New feature", may be someone will find it interesting enough to actually implement.

**Comment by scherepanov** [comment] 2021-11-26 16:30
Fixed in #253

**Closed by scherepanov** 2021-11-26 16:30 UTC
