### ISSUE TITLE
Feature Request: "No Titlebar" Option

### ISSUE THREAD

**Issue by jcuenod** [gTile/gTile#58] opened 2018-10-22 04:12 UTC
I use the `no-title-bar` extension. It would be great to have the option to hide title bars on windows that are gTiled. Originally I had thought this was something that no-title-bar could do: https://github.com/franglais125/no-title-bar/issues/61.

It still seems as though collaboration might be the best but I thought it would be worth filing this issue here. Is this possible/within scope?

**Comment by scherepanov** [comment] 2018-10-22 14:40
I am using "No title bar" extension with gTile and it works well and as expected.
It removes title bar when window is full screen or maximized vertically.
"No title bar" extension does not remove title bar when it is not full screen or not maximized vertically.

I understand you want to have option "remove title bar from any window"
I think it would be much better if "removing title bar" will be handled by separate extension. It can have keyboard shortcut to hide/show title bar for window with focus.

It is possible to include similar functionality into gTile. With "hide title bar" option window after "gTiling" will have no title bar.

I do not think this is a good idea, as it appears to be well out of scope of gTile.

Seems to be removing title bar would be better handled by separate extension.

Any comments?

**Comment by scherepanov** [comment] 2019-01-21 17:18
Not reproducable

**Closed by scherepanov** 2019-01-21 17:18 UTC
