### ISSUE TITLE
Grid sizes ignored?

### ISSUE THREAD

**Issue by amadeusp** [gTile/gTile#201] opened 2021-03-14 12:14 UTC
I am not sure if I simply don't understand how this is intended to work:
I set "3x2,4x4,6x4" as "Grid sizes" but any time I hit Super+Enter the grid in the UI is set to 8x6 (offering 6x4 or 4x4 as options via the two other grid size buttons in the UI).
My expectation in this situation was that at this point I would see the grid sizes I defined as options in the "Basic" setup.

My configuration:
* gTile version: 42
* OS: Manjaro 20.2.1 Nibia
* Kernel: x86_64 Linux 5.9.1-1-rt19-MANJARO
* Resolution: 3840x2160
* DE: GNOME 3.38.4
* WM: Mutter
* WM Theme: Adwaita-maia-compact-dark
* GTK Theme: Adwaita-maia-compact-dark [GTK2/3]
* Icon Theme: ePapirus
* Disk: 127G / 1.8T (8%)
* CPU: Intel Xeon W-3235 @ 24x 4.5GHz [34.0°C]
* GPU: AMD POLARIS10 (DRM 3.39.0, 5.9.1-1-rt19-MANJARO, LLVM 11.1.0)
* RAM: 3726MiB / 48133MiB

**Comment by scherepanov** [comment] 2021-03-14 15:40
yeah... but you need to login/logout for config change to take effect.
I know it is not a good design... submit a PR with a fix for it, I will accept.

**Comment by scherepanov** [comment] 2021-03-14 15:58
Apparently, I am losing my mind... change of grid sizes is properly supported a while ago. I still think it is not supported.
just check, change on grid config immediately shown up on pop-up gTile window.
I did several checks, works without any issues, exactly as expected. No need to logout/login or reboot.
May be, gnome-shell is to blame (very convenient to blame gnome-shell - it is very hard to prove, and recently gnome-shell do have a string of very bad bugs).
I am using gnome-shell version
gnome-shell --version
GNOME Shell 3.38.3

**Comment by scherepanov** [comment] 2021-03-14 16:37
Well... it is a recently introduced bug in gTile.

**Comment by scherepanov** [comment] 2021-03-14 16:44
Duplicate of #195

**Closed** 2021-03-14 16:44 UTC
