### ISSUE TITLE
GNOME Shell 3.36 support

### ISSUE THREAD

**Issue by articlecat** [gTile/gTile#118] opened 2020-03-10 00:11 UTC
To support GNOME Shell 3.36, [metadata.json](https://github.com/gTile/gTile/blob/master/metadata.json) needs to include `3.36` in `shell-version`. The [GNOME Shell Extension listing](https://extensions.gnome.org/extension/28/gtile/) should be updated as well.

**Comment by scherepanov** [comment] 2020-03-10 20:11
Generally speaking, new version of gTile with next version of gnome-shell support will be available with next Fedora release.
I cannot even check yet if gTile works on new version of gnome-shell. There is a ticket #117 about gTile not working on 3.35.
You can modify your local install for new version of gNome-shell, and post here message if it works. That will help.

**Comment by ejemba** [comment] 2020-03-11 13:51
It seems that the Clutter.TableLayout used by the extension has been purely removed from the gnome-shell repo.  [See commit 32185c17 on gitlab](https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/32185c17d029429ffadc536707c61fbc3b558256#db61fc3665deb101eaf5590f9f89ecf4800788e8_241_241)
The documentation ask to use Clutter.GridLayout instead but this is another way of managing layout and it changes a lot. TableLayout.pack() was about colNum and rowNum whereas GridLayout.attach() is more about left top width and height . 
I tried to patch on my install but the mapping between TableLayout and GridLayout would give me too much work :)

**Comment by ejemba** [comment] 2020-03-11 14:22
after a better read of the attach documentation and after looking at a [commit replacing TableLayout by GridLayout](https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/0749ac27ce3bed40c6311dea66b5ea8b4af44165)  in gnome repo. I was able to have no error when loading the extension but it does not work. I have the icon in the top bar but bindings are not working .
Something else has changed in gnome-shell 3.36.0
```
1463c1463
<             layout_manager: new Clutter.TableLayout()
---
>             layout_manager: new Clutter.GridLayout()
1482c1482
<             layout_manager: new Clutter.TableLayout()
---
>             layout_manager: new Clutter.GridLayout()
1501c1501
<             this.bottombar_table_layout.pack(button.actor, colNum, rowNum);
---
>             this.bottombar_table_layout.attach(button.actor, colNum, rowNum, 1, 1);
1519c1519
<             layout_manager: new Clutter.TableLayout()
---
>             layout_manager: new Clutter.GridLayout()
1544c1544
<         this.veryBottomBar_table_layout.pack(toggle.actor, 0, 0);
---
>         this.veryBottomBar_table_layout.attach(toggle.actor, 0, 0, 1, 1);
1548c1548
<         this.veryBottomBar_table_layout.pack(toggle.actor, 1, 0);
---
>         this.veryBottomBar_table_layout.attach(toggle.actor, 1, 0, 1, 1);
1552c1552
<         this.veryBottomBar_table_layout.pack(action.actor, 2, 0);
---
>         this.veryBottomBar_table_layout.attach(action.actor, 2, 0, 1, 1);
1556c1556
<         this.veryBottomBar_table_layout.pack(action.actor, 3, 0);
---
>         this.veryBottomBar_table_layout.attach(action.actor, 3, 0, 1, 1);
1587c1587
<                 this.table_table_layout.pack(element.actor, c, r);
---
>                 this.table_table_layout.attach(element.actor, c, r, 1, 1);
```

**Comment by scherepanov** [comment] 2020-03-11 15:00
Can you take some time and submit PR with a fix?
Also, can you read more docs, how to make code compatible with old versions of gnome-shell? 
A lot of users will be on older versions of gnome-shell for a while.
And, related problem, St removed actor support from bunch of classes, namely button.
Can you look, how to make code compatible with older version?

**Comment by ejemba** [comment] 2020-03-11 16:51
@scherepanov I don't know if your message was for me but my modification does not work yet. I can not make a PR.

What is OK
- There is no error, the extension now launches with GridLayout

What is KO
- key bindings does not work
- mouse click on top bar icons are not handled

**Comment by scherepanov** [comment] 2020-03-11 18:06
@ejemba yes, please make it working
Also, most likely with your changes gTile will be failing on older version of gnome-shell. It should be different code branch for new version of gnome-shell and previous.
Changes have to be tested on old and new version of gnome-shell.

**Comment by ejemba** [comment] 2020-03-11 18:18
@scherepanov I would like to but I can not fix it . Too much extra work . 
I'm "just" a user of the extension

**Comment by scherepanov** [comment] 2020-03-11 18:20
@ejemba  it is OK, thanks for some work you did.
Any takers on this issue?

**Comment by mwilck** [comment] 2020-03-12 12:13
Fellow suffering GNOME shell extension maintainers, you may want to have a look at [our issue for the hamster extension](https://github.com/projecthamster/hamster-shell-extension/pull/323). `Clutter.TableLayout` needs to be replaced by `Clutter.GridLayout` for 3.36.

**Comment by ejemba** [comment] 2020-03-12 19:07
Hi I just create a MR https://github.com/gTile/gTile/pull/119 , 
Not to be merged now.
I manage to make the extension usable but some UI quirks has to be fixed by someone else.
It is usable, I use it now, but is WIP

**Comment by renataogarcia** [comment] 2020-03-12 23:43
> Hi I just create a MR #119 ,
> Not to be merged now.
> I manage to make the extension usable but some UI quirks has to be fixed by someone else.
> It is usable, I use it now, but is WIP

@ejemba Thanks! Can confirm it's functional again to me as well.

**Comment by scherepanov** [comment] 2020-03-13 16:04
Now it is very interesting, how to make above changes compatible with older versions of gnome-shell.
May be, we should use gnome-shell version. For each changed line you should check if v <= 3.35 and use old code, for 3.36 and onward use new.
This will take some time to test.
Final goal is to have single code that will work on newer versions of gnome-shell and on older.

**Comment by ejemba** [comment] 2020-03-13 17:38
@scherepanov I'm leaving this for the maintainers of the extension. I'm even not a js/gnome developper. On top of that the fix is not complete. 
My action was really just to quickly help out the poor users who were told to wait for the next version of fedora on April 21st. Users of previous version of gnome won't be affected anyway if they don't install the fix.

**Comment by scherepanov** [comment] 2020-03-20 03:25
Hi everybody,
Please try master on gnome-shell v 3.36.
Post here if it works.
Post here if it does not.

**Comment by matte-Rhorn** [comment] 2020-03-20 12:34
I've tried master on Ubuntu 20.04 gnome-shell v 3.36. The extension is recognized, tray icon is displayed but it's not clickable. Extension is listed in Gnome Tweaks but it's not configurable, Ubuntu Extensions stops listing any installed extensions. Repeatedly trying to configure the extension trough  Gnome Tweaks panel leads Gnome to crash.

**Comment by scherepanov** [comment] 2020-03-20 14:06
Thanks for feedback!

**Comment by returntrip** [comment] 2020-03-20 14:15
Same issue for me (i.e.: unclickable icon) on Fedora 32 Silverblue Beta with Gnome 3.36

**Comment by yochananmarqos** [comment] 2020-03-20 14:37
The icon is also not clickable for me on Manjaro with GNOME 3.36.

**Comment by PoLoMoTo** [comment] 2020-03-20 18:59
Same issue with the unclickable icon on Arch with Gnome 3.36.  Also can't seem to open gTile with the accelerators either.

**Comment by jdus** [comment] 2020-03-20 19:31
I'm on Arch Linux as well, gnome-shell 3.36.0. Extension is loaded, icon is reacting and clickable, but this error is thrown:
```
JS ERROR: TypeError: this.actor.raise_top is not a function
show@/extension.js:1742:20
showTiling@/extension.js:700:18
toggleTiling@/extension.js:733:9
_onButtonPress@/extension.js:226:9
wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
```
Glad to help, but won't be able too look into it before tomorrow.

**Comment by scherepanov** [comment] 2020-03-20 19:35
Thanks, no need to post more feedback
Over weekend will get gnome-shell 3.36 and will make it working

**Comment by scherepanov** [comment] 2020-03-20 20:42
Can you try most recent master? That error should be fixed

**Comment by PoLoMoTo** [comment] 2020-03-20 20:49
It seems the icon is now gone for me on Arch with Gnome 3.36.  Does seem to load fine though, I can turn it on and off in the extensions app without issue.

**Comment by yochananmarqos** [comment] 2020-03-20 21:47
Everything seems to be working well with the latest commits. Thanks!

**Comment by returntrip** [comment] 2020-03-20 22:13
Tiling works but the config button does not work in Gnome Tweaks. I have also noticed that the tiling view is missing the "x" close button. Thanks!

**Comment by yochananmarqos** [comment] 2020-03-20 22:19
@returntrip: Use the new Extensions application, Tweaks isn't working right.

**Comment by jdus** [comment] 2020-03-21 09:37
Everything works for me now, the extension overall, the icon and the config menu in Tweaks.

**Comment by benruijl** [comment] 2020-03-21 10:07
Clicking on the icon I get:
```
Mar 21 11:06:42 PCNMG gnome-shell[889]: JS ERROR: TypeError: this.actor.raise_top is not a function
                                        show@/usr/share/gnome-shell/extensions/gTile@vibou/extension.js:1742:20
                                        showTiling@/usr/share/gnome-shell/extensions/gTile@vibou/extension.js:700:18
                                        toggleTiling@/usr/share/gnome-shell/extensions/gTile@vibou/extension.js:733:9
                                        _onButtonPress@/usr/share/gnome-shell/extensions/gTile@vibou/extension.js:226:9
                                        wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
```
and nothing else happens.

I also can't load the window with super+enter.

**Comment by skewty** [comment] 2020-03-21 15:28
I did a fresh install of Ubuntu 20.04 to test this out and the settings button (using tweak tool) isn't working.  No dialog is shown when the settings bug is shown.

It could be upstream because the built-in "Desktop icons" extension doesn't show a dialog either.

The built-in "Extensions" tool usually doesn't show extensions when it start up and toggling all extensions off with the switch in the headerbar and then back on again sometimes brings up an extension list.

Gnome alpha 3.36.0 seems to be of unusually low code quality :(.  (I had even more problems trying it out in Manjaro).

**Comment by matte-Rhorn** [comment] 2020-03-21 20:22
Extension works for me on Ubuntu 20.04 but only though the tray icon. Keybindings are not working and the extension is not configurable though the Gnome Tweak panel. But thank you very much for the quick improvement.

**Comment by scherepanov** [comment] 2020-03-21 23:45
Yes... it will be hard to make gTile working on gnome-she’ll 3.36

**Comment by PoLoMoTo** [comment] 2020-03-22 05:55
Does anyone know how to stop the new Extensions app from 'updating' gTile when you installed via git clone?  Seems to be updating to the last release and therefore breaks every time I log out.

**Comment by matte-Rhorn** [comment] 2020-03-22 10:12
> Does anyone know how to stop the new Extensions app from 'updating' gTile when you installed via git clone? Seems to be updating to the last release and therefore breaks every time I log out.

Unfortunately I experienced the same behavior in Ubuntu 20.04.

**Comment by scherepanov** [comment] 2020-03-22 16:30
There is an automatically assigned version number in metadata file. It is now different in extensions.gnome.org and git. My best guess Extensions app is using this number to auto update.
Please try to make version number to match. Let me know if it helps, will push fix to git

**Comment by scherepanov** [comment] 2020-03-22 19:14
Pushed fix for autodowngrade by Extensions app.

**Comment by scherepanov** [comment] 2020-03-22 22:46
One more bugs fix, should make master working for most users.

**Comment by jdus** [comment] 2020-03-23 09:43
Using it here on arch without any problems.

**Comment by murbanowicz** [comment] 2020-03-23 12:22
Any chance for this to be merged and published soon?

**Comment by scherepanov** [comment] 2020-03-23 14:17
Fix already merged into master.
For publishing, more testing needed for older versions of gnome-shell. There is some strange behaviour that I would like to fix.

**Comment by danleepw** [comment] 2020-03-25 16:44
git master crashes gnome-shell 3.36.0 when locking screen in Manjaro

**Comment by scherepanov** [comment] 2020-03-25 18:50
I am using Fedora 32 beta, and it is not a stable.
I think some problems can be with gnome-shell v 3.36 and Fedora 32 beta, not gTile.

**Comment by cwh1te** [comment] 2020-03-26 02:19
Testing on Manjaro 19.0.2 kernel 5.4.27 Gnome 3.36.0
Master branch is working great for me, no issues whatsoever
Can confirm very low code quality for this Gnome version - crashed my desktop during update, and have encountered numerous bugs in just the last hour

**Comment by danleepw** [comment] 2020-03-26 02:29
My screen lock has no more issue after disabling gtile. i agree that gnome-shell 3.36.0 is unstable with some extension.

**Comment by jdus** [comment] 2020-03-26 06:32
I can also confirm, that the shell will crash with gTile enabled. It's perfectly fine when actively working, but as soon as the screen is locked, gnome-shell crash. I'm not sure if gTile is directly responsible for the crash. I think it rather triggers something else to crash and tear down the shell.

**Comment by scherepanov** [comment] 2020-03-26 13:40
Gnome-shell crashing on screen locking is a serious issue. I do not think new version of gTile should be deployed to EGO until resolved.
gTile definitely trigger something that is causing gnome-shell to crash. New version of gnome-shell removed a bunch of API calls, and seems to be change behaviour of other API calls. I can see warning about gTile that were not present in previous versions of gnome-shell.
Will investigate.

**Comment by scherepanov** [comment] 2020-03-29 04:45
I checked gTile against gnome-shell v 3.32 on my desktop, and v 3.29 and 3.36 on Boxes VM.
I have not found that gnome-shell is crashing on screen locking.
It appears Fedora 32 Beta is evolving very fast, now it is by far more stable that it was a week ago.
It is possible that some problem was fixed and gTile is not causing gnome-shell crashing on screen lock. though I doubt it.
So.... current master looks good enough.
I marked current master as release V34, and submitted it to EGO.
Will handle all problems as they will be reported by users.

**Comment by mattjcj** [comment] 2020-03-29 18:49
I experienced the same issues when updating Manjaro : when locking the screen it kept unlocking and locking again a few times until gnome shell crashed. Since I didn't follow Manjaro's guidelines to upgrade gnome (log in to tty and upgrade from there), I thought this was the problem. It was quite a fresh install so I just made a clean install of the latest version of the distro, and I don't have this problem anymore. But now I have the unclickable gTile icon issue. Shortcuts (global resize presets) are not working as well. Also I still managed to get gTile to show up once, after a restart, but then not anymore.

**Comment by topjor** [comment] 2020-03-29 22:25
I also use manjaro and updated via tty with no graphical environment active so the recommended way. I am using wayland and I can confirm its gTile or a combination of gTile and another extension that causes crashes upon unlocking, for me it is after unlocking, I tried a few times and if gTile is enabled it crashes, but weirdly, only when the extension is active when logging in, when activating the extension after I am logged in, this issue does not seem to occur for some reason. (I just installed the git master version)

**Comment by scherepanov** [comment] 2020-03-29 22:28
gnome-shell 3.36 crashing on screen lock/unlock have been moved to #124 
Please post there.

**Comment by scherepanov** [comment] 2020-04-24 14:35
Looks like gTile works OK on gnome-shell 3.36.

**Closed by scherepanov** 2020-04-24 14:35 UTC
Labels: help wanted
