### ISSUE TITLE
Gtile breaks top bar active layout since gnome-1.3.34

### ISSUE THREAD

**Issue by makaleks** [gTile/gTile#101] opened 2019-11-13 14:47 UTC
When gtile is enabled, left buttons of gnome top bar can not be clicked when cursor at the top edge of the screen (requires switch to gnome overview mode). When disabled, the problem disappears immediately

[screencast attached](https://drive.google.com/file/d/1iZGEbCEGDe8a85JGUXWvWbJrjQ5oGiqG/view?usp=sharing)

**Comment by scherepanov** [comment] 2019-11-14 17:03
Interesting. I do not see how it can happen. Anyway, will check.

**Comment by scherepanov** [comment] 2019-11-15 04:59
I can clearly see from your screencast, how this happens. I am trying to reproduce, on same Fedora 31 gnome-shell 3.34.1, and it does not show up.
I suspect it is not gTile problem, but gnome-shell.
Also, I do not really understand, how it is possible.
Only remote possibility I can see, if those buttons on top panel are using same shortcuts as used by gTile. It is easy to check - in gTile preferences, disable global shortcuts, then disable/enable gTile, and see if problem persist.

**Comment by scherepanov** [comment] 2019-11-15 05:52
From other side, gTile in gnome-shell 3.34.1 do have some strange warnings about button in top bar. I will investigate.

**Comment by scherepanov** [comment] 2019-11-19 15:23
Can you try to re-install gTile from scherepanov/gTile
You need to logout/login after reinstall
Let me know how it works for you

**Comment by makaleks** [comment] 2019-11-19 15:42
That did not help, sorry

**Comment by scherepanov** [comment] 2019-11-19 15:44
May be you can look in log, to see if anything unusual?
Run
journalctl
See what happens after last login, with new version of code

**Comment by makaleks** [comment] 2019-11-19 16:16
I did not see gtile mentioned anywhere in logs
https://drive.google.com/drive/folders/1e50hw3iNGY2UIoWfewoazyUx41v2GZer?usp=sharing

**Comment by makaleks** [comment] 2019-11-19 17:05
gnome inspector (alt+f2, 'lg') shows some objects above top-left buttons with heights 36 or even 38, while my top bar's height is 27 only. I don't know how to identify these objects. It can even be not what we need.
https://drive.google.com/file/d/1qDPD0b5q5GLQ9GOHSI0SZYbhxV-Qj8xr/view?usp=sharing

**Comment by scherepanov** [comment] 2019-11-19 18:11
No idea what to do

**Comment by mrjohnson22** [comment] 2019-12-01 17:33
This still happens on the latest version of gTile (V28) and gnome-shell (gnome-shell-3.34.1-4).

One way to reproduce is to do the following:
* Open two windows, each one in a different workspace
* Focus on one of the windows
* Turn on gTile
* Switch to the other workspace (which puts the window in that workspace in focus)

After doing this, putting the mouse at the top of the screen above the top-left panel buttons won't highlight them, no matter which window is in focus. Turning off gTile immediately fixes this.

The problem also doesn't go away when in the Overview, as moving the mouse to the top of the screen above the "Activities" button and clicking doesn't exit the Overview, meaning the "Activities" button must not be highlighted.

Examples:
* Before:
![mouseTopHoverGood](https://user-images.githubusercontent.com/8988672/69917644-1c12b900-1436-11ea-8c7c-0e2a9d1f3079.png)

* After:
![mouseTopHoverBad](https://user-images.githubusercontent.com/8988672/69917646-21700380-1436-11ea-9bd7-17470ba9d3b8.png)

**Comment by scherepanov** [comment] 2019-12-02 19:05
Still cannot reproduce
Very strange
Can I ask you to disable gTile icon in top panel (in gTile preferenes, on first tab) and see if problem persist?
Also, if you can enable gTile debug (in gTile preferences) and see if any errors popping up in logs?

**Comment by mrjohnson22** [comment] 2019-12-10 03:55
The problem persists even when the icon is disabled.

The logs do show something interesting: whenever the mouse is moved to the top-left of the screen above "Activties" or the current app button (and invokes the bug of the button not getting highlighted), `gTile refreshGrids` gets printed. Moving the mouse left and right causes that message to print repeatedly.

**Comment by scherepanov** [comment] 2019-12-10 17:05
That is interesting.
Can I ask you to do more debug.
There are 3 places where refreshGrids are being called - updateRegions, _onButtonPress, _onMouseLeave.
updateRegions already have log entry before call to refreshGrids:
    log("updateRegions");
but you are not mentioning it.
Can you edit in text editor file
~/.local/share/gnome-shell/extensions/gTile@vibou/extensions.js
and add log entry before call to refreshGrids in two more places, _onButtonPress and _onMouseLeave. Then logout/login, and see logs.
I suspect it is _onMouseLeave.. which means it is a bug in gnome-shell... but to prove will need more debugging.

**Comment by mrjohnson22** [comment] 2019-12-20 04:30
Sorry for taking so long. Your hunch was right: updateRegions is being called in _onMouseLeave. After adding log entries in all three of those functions, only the log of _onMouseLeave gets printed when I move the mouse to the top-left of the screen.

**Comment by scherepanov** [comment] 2019-12-23 21:21
That squarely points to a bug in gnome-shell.
Let's try to do workaround.
Can you modify code.
There are functions show (starts around line 1623) and hide (line 1653).
Can you add last line to show:

this.actor.scale_x = this.normalScaleX;

and add last line to hide:
this.actor.scale_x = 0;

Please let me know how it goes

**Comment by mrjohnson22** [comment] 2020-01-13 04:00
That workaround indeed fixes the problem. I've had it enabled all day and the issue hasn't happened once.

**Comment by scherepanov** [comment] 2020-01-13 15:13
Glad to hear
I will add this fix to a code over weekend.
Will take some time to deploy to EGO

**Comment by scherepanov** [comment] 2020-02-10 14:57
Can you check that scherepanov/gTile repo fixes this issue.

**Comment by mrjohnson22** [comment] 2020-02-17 18:05
Yes, it works!

**Comment by scherepanov** [comment] 2020-02-17 18:07
Thanks for testing
This fix will eventually be merged into master.

**Closed** 2020-03-16 02:22 UTC
